### ISSUE TITLE
Word wrap and preserving new lines support?

### ISSUE THREAD

**Issue by TheChilliPL** [muzuiget/dualsub-support#124]
If I have YouTube on only half of my screen, I can't see a part of the subtitles as they go off the screen. Is there an option to enable word wrapping? I tried doing something with CSS but for some reason, dev tools get really laggy when I open them on YouTube.
Also, the new line characters are not preserved and sometimes it's harder to understand that way if there's no punctuation.

**Comment by muzuiget** [comment]
All right, it looks like the line wrapping is issue, I will redesign the handling in later version.

By the way, a work around is use [this plugin](https://dualsub.netlify.app/en-us/plugin?id=style-youtube-font-size-scaling) to scale the font size.

The new line characters be removed because the machine translating, for example, some CC subtitle may has this dialogue:

```
The quick brown fox jumps 
over the lazy dog
```

The translated text is more accurate in single line than two lines.

So if we don't use the machine translating, it is better keep the  new line characters.

**Comment by TheChilliPL** [comment]
What about having an option in the settings to preserve new line chars?

**Comment by Wizek** [comment]
+1 for the simple option for now. It would be nice to have a quick fix if someone doesn't want to machine-translate.

And later on the machine translation + new-line preservation scenario can be better supported as well.

**Comment by muzuiget** [comment]
Can you provide any video subtitle you want to keep newline by default? Are they  CC or auto-generated subtitles?

**Comment by shxvank** [comment]
is there a way to make a plugin where if the subtitle contains a comma, it will return a new line?

![Screen Shot 2020-08-03 at 9 46 59 PM](https://user-images.githubusercontent.com/28308261/89243813-e7618d80-d5d2-11ea-813a-5dc259377cc1.jpg)

**Comment by muzuiget** [comment]
Auto line wrap implemented in v1.13.0
