### ISSUE TITLE
dualsub-support can't work on youtube

### ISSUE THREAD

**Issue by 4codingHu** [muzuiget/dualsub-support#134]
There's no language.
![image](https://user-images.githubusercontent.com/20881665/89186230-10335400-d5ce-11ea-89c5-a2d26f580802.png)

**Comment by 4codingHu** [comment]
https://www.youtube.com/watch?v=BKPIzg3vkXs

**Comment by 01MrHacKeR01** [comment]
> https://www.youtube.com/watch?v=BKPIzg3vkXs

because there is no subtitle to translate
dualsub is translating subtitles so it must be one subtitles at least to be translated to ur language
english to japanese
and the most english videos on youtube has auto-subtitles that is why u can use dualsub
but there is also videos has subtitle in it
so the video must has subtitle to be translated by dualsub

**Comment by muzuiget** [comment]
Not a bug, the YouTube video itself should provides some subtitle,that is the subtitle icon showed in the player.
