### ISSUE TITLE
Not working correctly with Amazon Primevideo

### ISSUE THREAD

**Issue by hashkrish** [muzuiget/dualsub-support#141]
It is not providing the correct subtitle for the video in the amazon prime video. I think it fetch some other videos subtitle in the playist/season

**Comment by muzuiget** [comment]
Please provide a test video url, or some screenshots, what difference between the native subtitle menus and the dualsub subtitle menus?

**Comment by 01MrHacKeR01** [comment]
> It is not providing the correct subtitle for the video in the amazon prime video. I think it fetch some other videos subtitle in the playist/season

i recommend u if u have problems with translation add subtitle to extension that add it to website
because google translation not always makes u understand it is reboot
this website u may find subtitles
(no offense , developer but sometimes i really cant understand what happening or dont understand because of google translation
but dualsub timing is perfect not like subtitles may be late or early

**Comment by hashkrish** [comment]
![image](https://user-images.githubusercontent.com/29514440/90998670-4fa7fb80-e5e2-11ea-86a8-65aa940b01f1.png)

![image](https://user-images.githubusercontent.com/29514440/90998764-82ea8a80-e5e2-11ea-9423-49c99c7a55cc.png)

The below one is prime video subtitles and the above two lines are from Dualsub. The first line is English detected by Dualsub, second line is machine translation.

**Comment by muzuiget** [comment]
Please provide the video url.
