### ISSUE TITLE
I can't seem to adjust the location of the Furigana.

### ISSUE THREAD

**Issue by Mctoodles-NNN** [muzuiget/dualsub-support#143]
I can't seem to adjust the location of the Furigana.  How do I tweak the Furigana to place it above the Kanji?  The Kanji covers the Furigana and I can't read it.  I can move it left or right but I can't way above the Kanji to read.

**Comment by muzuiget** [comment]
Are you using Dualsub on Netflix? The furigana is inline as [Closed Caption Content](https://dualsub.netlify.app/en-us/appendix?id=what-is-closed-caption) in the subtitle text, eg:

```
故郷(ふるさと)へ続(つづ)いても
```

So, to move the furigana above the kanji.

First, check the setting option [Remove Closed Caption](https://dualsub.netlify.app/en-us/setting?id=remove-closed-caption), then the the subtitle text will become:

```
故郷へ続いても
```

Then use the Dualsub "Language Toolkit" to re-generate the furigana:

* "Language Toolkit" menu select "Japanese Analysis".
* "Theme Style" menu select "Japanese Learning".

Because the furigana is re-generate from kanji with machine, maybe not the same as the human make ones. eg: `故郷` maybe re-rengerate as `こきょう`, not `ふるさと`.

**Comment by Mctoodles-NNN** [comment]
I'm using Youtube or Bilibili.  Not Netflix.

**Comment by muzuiget** [comment]
You better provide the screenshots or video url.
