### ISSUE TITLE
Apply to "https://www.hulu.jp/"

### ISSUE THREAD

**Issue by fujita2020** [muzuiget/dualsub-support#144]
Hi.
Could you add the URL "https://www.hulu.jp/" to the apply list of this add-on?
In japan, "https://www.hulu.jp/" is only accessible as hulu.
I'd like to try using this add-on in it.

Thank you.

**Comment by muzuiget** [comment]
I'd like to, but the problem is Hulu JP doesn't provide a easy way for testing, it requires me to have a payment method register a account, it is unavailable outside Japan.

So, to support Hulu JP, I need an testing account, or a testing video without login, If you like to provide one, you can send it via private message on Github.

**Comment by NaruseDaigo** [comment]
Probably for the same reason, This add-on is not activated on the following sites.
"https://www.amazon.co.jp/Amazon-Video/* "
"https://disneyplus.disney.co.jp/"
"https://www.hulu.jp/“
These all include "jp" domains.

If there's anything I can do to help, please let me know.

**Comment by muzuiget** [comment]
I am not sure these websites have the **same code-base** as it on USA.

If they have same code-base, I just need add some new url patterns to the code, then everything should work fine.

If not, I need a testing account on these website, analysis the website code to make Dualsub adapt it. 

But they even not provide a free/trial account, register a new account is not easy.
