### ISSUE TITLE
can't move the subtitle , that's not cool

### ISSUE THREAD

**Issue by gumpsimon** [muzuiget/dualsub-support#287]
draging the subtitle is a very good function for me. but i cant move the subtitle in the youtube player for a new version , maybe i have to use a lower version. disappointed.

**Comment by gumpsimon** [comment]
it's seemed that the lower version dont surpport traslation any longer , how can i solve it😧

**Comment by muzuiget** [comment]
Moving the subtitles with the dragging is remove in the v1.64.0, but the v1.63.0 still works.

Maintain this feature is rather painful, because Dualsub supports many websites now, even mobile browsers, the dragging only on works on Chrome desktop. If we want to compatible all browsers, there are lot of codes to added.

Also I want auto position the subtitles and scale the font size in different video layout, it's difficult to compatible with the dragging behavior, so I remove this feature.

Here are the solutions:

1. There is a "Magin Bottom" setting option in the popup page "Quick Settings" tab, you can change this value to make the position higher or lower, this value apply globally.

2. You can use a "style" type Dualsbub plugin, for example, there is a "YouTube Auto Scaling" code is generated for you:

```
.ytd-page-manager .dualsub-renderer {
    margin-bottom: -50px;
}
.ytd-page-manager[theater] .dualsub-renderer {
    margin-bottom: -40px;
}
.ytd-page-manager[fullscreen] .dualsub-renderer {
    margin-bottom: 0;
}
```

You can change the `margin-bottom` value to your prefer in difference layout.

**Comment by gumpsimon** [comment]
Thanks a lot. You can add these help documents to the prompts of the new version. Acceptable, modifying the style is a method I didn't expect.
