### ISSUE TITLE
Turn on/off the subs easily

### ISSUE THREAD

**Issue by Rober19** [muzuiget/dualsub-support#342]
Hi!

all the parameters already in are just awesome, I was wondering if it would be possible to take in/out the subtitles quickly 

> like this
![image](https://user-images.githubusercontent.com/28882108/134419681-093cfdf2-909b-42da-9ee9-45e21cae3298.png)

😄

**Comment by muzuiget** [comment]
There are already several ways to "turn off" the subtitles. I don't want to add a new one, otherwise the UI interaction will be messy.

If you just want the subtitles to disappear temporarily because the subtitles are covering the player menu, I suggest using the hotkey.

To go the extension setting page, switch to "Plugin" tab, add a new plugin, type "Script", use the code below:

```
document.addEventListener('keydown', (event) => {
    if (event.altKey && event.key === 't') {
        const node = document.querySelector('.dualsub-renderer');
        node.style.display = node.style.display === '' ? 'none' : '';
        return;
    }
});
```

Then check the website checkbox you want to enable. When you press `Alt + t`, it will toggle the subtitle display.

I prefer add opacity, so it can notices you the extension is working: 

```
document.addEventListener('keydown', (event) => {
    if (event.altKey && event.key === 't') {
        const node = document.querySelector('.dualsub-renderer');
        node.style.opacity = node.style.opacity === '' ? '0.2' : '';
        return;
    }
});
```

**Comment by Rober19** [comment]
I didn't know the plugin option, that would be great as well.
Thank you for the suggestion!
