### ISSUE TITLE
Support Sino Vietnamese

### ISSUE THREAD

**Issue by sonbui00** [muzuiget/dualsub-support#371]
In Vietnam, we have own system ([Sino Vietnamese](https://en.wikipedia.org/wiki/Sino-Vietnamese_vocabulary)) to spell chinese character (like pinyin). This is very helpful for Vietnamese to learn and understand chinese. Do you have plan to support this? I can try to write a library to convert chinese character to Sino Vietnamese.
Additionally, if the extension can allow inject External Subtitle Files via js code, I can try to inject Sino Vietnamese subtitle automatic via js code (use this extension [Scripty - Javascript Injector](https://chrome.google.com/webstore/detail/scripty-javascript-inject/milkbiaeapddfnpenedfgbfdacpbcbam)).

**Comment by muzuiget** [comment]
Currently Dualsub has already supported [load local subtitle files](https://www.dualsub.xyz/docs/load-external-subtitle-files) and execute user-scripts.

So there are two solutions:

1. Pre-process your local subtitle files, add/replace the vocabularies in the subtitle context, the load them into Dualsub.

2. If you want to process it on the fly, you can execute user-scripts to change the Dualsub HTML node `.dualsub-renderer` directly, but you can only change it on the player on the pausing status, when the player on playing status, the `.dualsub-renderer`  will auto-reset.

If you want the displaying like pinyin, currently I am not able to support it, because I don't have any tech knowledge on it.
