### ISSUE TITLE
Support local video files

### ISSUE THREAD

**Issue by Manishearth** [muzuiget/dualsub-support#372]
It's possible to simply open local video files in the browser, and they play as usual using a regular `<video>` tag.

Since the extension has support for uploading custom subtitle files, it would be nice if it would be possible to use local video files as well by opening them in the browser and then adding the custom subtitle files.

**Comment by muzuiget** [comment]
Yes, is possible, here is a quick & dirty solution.

**Make sure the video file can be play in Chrome**

Open a  blank page `about:blank`, then "drag & drop" the video file in it, to check if Chrome shows a embed player and plays the file.

If Chrome popup a save-as file dialog, rename to video file extension name to `.webm`(eg: `test.mkv` to `test.webm`) and try again.

**Create a script type plugin in Dualsub**

![Screenshot_20220207_204506](https://user-images.githubusercontent.com/330812/152790557-ee503692-a1ad-42f0-82f3-2eb144aa127d.png)

Here is the code for you to paste:

```
document.body.addEventListener('dragover', function(event) {
    event.preventDefault();
});
document.body.addEventListener('drop', function(event) {
    event.preventDefault();
    const file = event.dataTransfer.items[0].getAsFile();
    const video = document.querySelector('video[src]');
    video.src = URL.createObjectURL(file);
});
```

**Replace the video file**

Open [a random YouTube video page](https://www.youtube.com/watch?v=JkaxUblCGz0), then "drag & drop" the locale file in it, then the YouTube player will the local file.

* You don't need to change the extension name to `.webm`, because the JavaScript will force it to play inline.

* The progress bar time is still adapt for the original video, so you need to find a longer YouTube video for your local file. eg: if your local file is 50 minutes long, you need a 50+ minutes YouTube video for the replacement.

---

The final solution is create a standalone website for this use case, see #315 I posted before, you can check it out with Google Translate if you're interested.

**Comment by Manishearth** [comment]
Sweet, thank you!

**Comment by muzuiget** [comment]
Now you can try `player.dualsub.xyz` with Dualsub v1.79.0.

Open `https://player.dualsub.xyz/?if=p` then drag a video file and subtitle files to the page.

**Comment by Manishearth** [comment]
Thanks!
