### ISSUE TITLE
[Bug] Doesn't work for UK's Amazon Prime Video

### ISSUE THREAD

**Issue by PineappleIOnic** [muzuiget/dualsub-support#526]
This extension does not work for amazon prime video in the UK which is under the address amazon.co.uk instead of [amazon](https://www.primevideo.com)

**Comment by muzuiget** [comment]
Because people think the domain `amazon.*` as a shopping website, not a video website, so I don't like to request these domain in the extension.

But the extension may supports these domains, you can load a special version Dualsub.

Download the `dualsub-v2.7.6-am.zip` file in #418.

And load it in the Developer mode in `chrome://extensions/`.

It can be enabled in the time with the Chrome Store version.

**Comment by PineappleIOnic** [comment]
Apologies but I am using Firefox, not chrome so I am unable to install the extension

**Comment by muzuiget** [comment]
Dualsub 2.x is a Manifest V3 extension, Firefox currently not support Manifest V3 extenison, so you only can use a Chromium-base browser.

**Comment by PineappleIOnic** [comment]
Ah, I see. Apologies then! Have a great day
