### ISSUE TITLE
"Waiting for server response" is always displayed on YouTube.

### ISSUE THREAD

**Issue by takumaim** [muzuiget/dualsub-support#547]
Hello Dualsub team,

I use it to watch YouTube, but the Subtitle Language setting in Standard Mode can only be selected as "(auto-generated)+", and it always remains in a waiting state for server response. When will this be improved? Previously, the Subtitle Language setting was "(auto-generated)". And I have confirmed the "200 OK" on "https://api.dualsub.xyz/".

Thank you.

Tak

**Comment by muzuiget** [comment]
`(auto-generated) +` is a new auto-generated subtitle in standard mode, base on OpenAI Whisper model.

OpenAI Whisper does better than YouTube because it adds punctuation.

You can also get the YouTube `(auto-generated)` back by setting a hidden config argument.

See #538, it is written in Chinese, but you can Google Translate it.

**Comment by takumaim** [comment]
Thank you for your response. When I changed the language of the videos targeted for Machine Translation to English using "(auto-generated) +," these issues were resolved. I'm not sure of the reason, but it seems that an error occurs when either "Close" option is selected.

**Comment by muzuiget** [comment]
This is expect behavior.

`Waiting for server response...` is a placeholder when the server is transcribing the audio file, when the transcribe done, the placeholder will be removed and replaced by the transcribe result.
