### ISSUE TITLE
Translation doesn't work: { This subtutle time point has exceeded the free translation quota }

### ISSUE THREAD

**Issue by ataberken** [muzuiget/dualsub-support#572]
Hello,

I am trying to translate from French to English, but i am getting below error when i activate the tool on Disney+: { This subtutle time point has exceeded the free translation quota }

The tool can read the subtitles well, if translation is closed.

Thanks in advance for the support! :)

**Comment by muzuiget** [comment]
Because the machine transition is a paid feature, it uses our own server sto do the translation, see [this docs](https://www.dualsub.xyz/guide/paid/overview.html). 

Note that Disney+ itself provides many human translation, you can see them in the Disney+ native subtitle menu, these languages menu items also show in the Dualsub "Subtitle Language" column menu. So you can select the English and French language in the "Subtitle Language" column menu, and keep the "Machine Transition" column as `Close`.
