### ISSUE TITLE
RTL Languages (such as Hebrew, Arabic) are aligned as LTR

### ISSUE THREAD

**Issue by idanrm** [muzuiget/dualsub-support#577]
Subtitles translated to Hebrew and Arabic, which are right-to-left languages, are rendered incorrectly. For example, the punctuation appears wrong and sometimes the last part of the sentence appears before the first part, etc.

Thanks.

**Comment by muzuiget** [comment]
The issue is somewhat complex, as I lack extensive experience in this area.

Displaying Arabic, a right-to-left script, on browsers involves multiple methods, each suited to different scenarios. The complexity increases when mixing with left-to-right scripts like English.

* The inherent text layout properties of Arabic characters.
* Unicode typographic characters, such as `U+202B`.
* Various CSS text layout methods, for instance, `direction: rtl`.

You need to specify the type of subtitles in question: are they original subtitles provided by the website or machine-translated subtitles?

If they are the website's original subtitles, is the website's native subtitle functionality working correctly?

**Comment by idanrm** [comment]
It happens in all cases, original subtitles and machine translation. For example, if there are original, auto-generated or machine-translated Arabic subtitles in a YouTube video, YouTube would show them correctly, while Dualsub renders the same subtitles in all cases incorrectly.
When the direction of the text is changed (for example, "direction: rtl"), it would show it correctly when there is a mix between, say, English and Arabic text.

**Comment by muzuiget** [comment]
Previously, I encountered a similar issue #337, and I simply made modifications based on the suggestions from the questioner as I didn't have knowledge in this area.

However, now with ChatGPT, I have a deeper understanding in this area.

The modification method in #337 is incorrect. HTML `&rlm;` indeed needs to be converted to `U+200F`, not `U+202B`. This is because "semantic strings" and "visual strings" should not be confused:

When extracting semantics from caption files `.vtt`, it is indeed necessary to use `U+200F`.

When there is a need to "draw" a "semantic string," there are two methods:

* Dynamically adding `U+202B` as a special character.
* Or using CSS.

**Comment by muzuiget** [comment]
When you select Arabic/Hebrew in the YouTube native subtitle menu, it indeed inserts the `dir="rtl"` attribute.

The Dualsub "Native Mode" simply merges the text of two subtitles and does not control the subtitle HTML. This means Dualsub cannot modify HTML based on language because the YouTube subtitle code continuously refreshes (or regenerates) the subtitle HTML.

**Comment by muzuiget** [comment]
In the Unicode bidirectional writing direction property, punctuation belongs to "Neutral characters." Its display direction is determined by several factors, including the direction of preceding and following characters, the direction of the entire sentence, or even the default direction of the entire webpage.

Therefore, I tend to preserve the original state and let users use CSS to precisely control the writing direction of each sentence.

**Comment by muzuiget** [comment]
Here is the CSS to fix the direction.

```css
/* native mode */
.caption-visual-line:nth-child(1) {
   direction: rtl;
}
.caption-visual-line:nth-child(2) {
   direction: ltr;
}

/* standard mode */
.dualsub-renderer .subtitle-1 {
   direction: rtl;
}
.dualsub-renderer .subtitle-2 {
   direction: ltr;
}
```

Before:

![Screenshot_20240214_130528](https://github.com/muzuiget/dualsub-support/assets/330812/6b0a35bc-5969-4d23-bed6-aabd27bbc9a5)

After:

![Screenshot_20240214_130624](https://github.com/muzuiget/dualsub-support/assets/330812/a68a8875-696e-4a67-92be-916eefe5e240)

**Comment by idanrm** [comment]
Thank you, it works. However, I think it is a bit cumbersome to add this code everytime we watch a video, it doesn't fit for everyday use. Isn't there a way for the extension to inject this CSS code whenever the selected language is an RTL language? (there are lists of RTL language codes on Google)

**Comment by muzuiget** [comment]
There are two ways: create a custom extension, or use userscript extension.

**1. Create a custom extension**

Create a `manifest.json` file:

```
{
    "manifest_version": 3,
    "name": "Bidi",
    "version": "0.1.0",
    "content_scripts": [
        {
            "matches": [
                "https://www.youtube.com/*"
            ],
            "css": [
                "styles.css"
            ]
        }
    ]
}
```

Then create a `styles.css` in the same directory, the content is the CSS code I posted above.

**2. Use userscript extension**

I also write a small userscript extension [WildMonkey](https://chromewebstore.google.com/detail/wildmonkey/jlffehhlfkdbdheffcaekpmkhfphmhpg).

![Screenshot_20240215_005245](https://github.com/muzuiget/dualsub-support/assets/330812/7e580dad-8905-4706-97e2-639e24ef4066)

**Comment by idanrm** [comment]
Thank you, it works well. For me (and for anyone who will see this issue) the problem is solved, however, why isn't it possible to integrate this CSS change into the Dualsub extension itself?

Thanks
